### PR TITLE
updated demo apps

### PR DESCRIPTION
**Pull request by rkreienbuehl**
I optimized the demo apps UI a bit and added zoomIn and zoomOut buttons in the desktop version.

### CODE REVIEW

**Comment by p-lr** [comment]
I tested your branch and I like the lateral navigation on the desktop app, along with the zoom buttons and animation!
However, in order to reuse existing demos while having specific desktop ui defined at top level, you had to add a "GlobalVM" which adds complexity to the existing code. Ideally, we would do the same without having to introduce a global viewmodel, which acts as an implicit dependency. I believe this is important to have the simplest demo app possible.
So far, I thought about two ways:
1. Have a specific desktop app which doesn't share much of UI code with common code.
2. Check for current platform in each screen and only add buttons when the platform is desktop. However, this would add clutter in common code, just for the desktop app.

So I prefer 1, even if we no longer reuse common code for desktop app. If we think about it, this isn't that surprising (when UIs start to differ, it becomes hard to share common code).
What do you think?

**Comment by p-lr** [comment]
Meanwhile, I'm making significant progress on the optimization side. In my `bitmap-pooling` branch, I found a way to use kotlinx.io `Source` as replacement for the former `InputStream`. Basically, instead of allocating a whole `ByteArray` everytime we fetch a tile, we can read it as a stream. The goal is to write that stream into an existing `ByteArray` (from the pool).

**Comment by rkreienbuehl** [comment]
I agree and I also thought about it.
What do you think about an approach like this on the example of `AnimationDemo `:

commonMain
```kt
expect object AnimationDemo : Screen

@Composable
fun AnimationDemo.View(screenModel: AnimationDemoVM) {
    val onRestart: () -> Unit = screenModel::startAnimation

    Column(Modifier.fillMaxSize()) {
        MapUI(
            Modifier.weight(2f),
            state = screenModel.state
        )
        Button(onClick = {
            onRestart()
        }, Modifier.padding(8.dp)) {
            Text(text = "Start")
        }
    }
}
```

iosMain/androidMain
```kt
actual object AnimationDemo : Screen {
    @Composable
    override fun Content() {
        val screenModel = rememberScreenModel { AnimationDemoVM() }

        View(screenModel)
    }
}
```

desktopMain
```kt
actual object AnimationDemo : Screen {
    @Composable
    override fun Content() {
        val screenModel = rememberScreenModel { AnimationDemoVM() }
        val coroutineScope = rememberCoroutineScope()

        val zoomIn: () -> Unit = {
            coroutineScope.launch {
                screenModel.state.scrollTo(
                    screenModel.state.centroidX, 
                    screenModel.state.centroidY, 
                    screenModel.state.scale * 1.5f, 
                    TweenSpec(800, easing = FastOutSlowInEasing)
                )
            }
        }

        val zoomOut: () -> Unit = {
            coroutineScope.launch {
                screenModel.state.scrollTo(
                    screenModel.state.centroidX,
                    screenModel.state.centroidY,
                    screenModel.state.scale * 1.5f,
                    TweenSpec(800, easing = FastOutSlowInEasing)
                )
            }
        }

        Box(modifier = Modifier.fillMaxSize()) {
            View(screenModel)
            Column(modifier = Modifier
                .align(Alignment.BottomEnd)
                .padding(bottom = 10.dp, end = 10.dp),
                verticalArrangement = Arrangement.spacedBy(5.dp)
            ) {
                Button(modifier = Modifier.size(40.dp),onClick = { zoomIn() }) {
                    Text("+")
                }
                Button(modifier = Modifier.size(40.dp), onClick = { zoomOut() }) {
                    Text("-")
                }
            }
        }
    }
}
```

**Comment by p-lr** [comment]
Interesting approach. Looks good to me!
Could you please do this change, without other things like common http client? (for now).

**Comment by rkreienbuehl** [comment]
I just pushed the changes

**Review by p-lr — APPROVED** [review]

**Comment by p-lr** [comment]
Thanks!

**Comment by p-lr** [comment]
I refactored a bit (only changing function names). Now I'll have to rebase my `bitmap-pooling` branch, as the demo changed significantly.

**Pull request merged**
